source 'https://rubygems.org'

ruby '3.3.11'

# Web framework
gem 'rails', '~> 8.0.0'
gem 'puma', '~> 6.4'

# Database
gem 'sqlite3'

# Frontend
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jsbundling-rails'
gem 'cssbundling-rails'
gem 'sprockets-rails'

# JSON
gem 'jsonapi-serializer'

# Graph search & AI algorithms
gem 'algorithms'

# Development/Testing
group :development, :test do
  gem 'debug'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'web-console'
end
